variables:
  ShortGitHash: ''

jobs:

- job: Build_PrivacyAmplification_On_Self_Hosted_Agent
  timeoutInMinutes: 30
  pool:
    name: PrivacyAmplificationPool

  steps:
  
  - script: |
      echo $(Build.SourceVersion)
      set gitHash=$(Build.SourceVersion)
      set shortHash=%gitHash:~0,7%
      echo %shortHash%
      echo ##vso[task.setvariable variable=ShortGitHash;]%shortHash%
    displayName: 'Get ShortGitHash Script'
  
  - task: CmdLine@2
  displayName: 'Execute cmake for glslang'
  inputs:
    script: |
     mkdir "PrivacyAmplification/glslang-master/build"
     cd "PrivacyAmplification/glslang-master/build"
     cmake ..
    failOnStderr: true
  
  - task: VSBuild@1
  displayName: 'Build glslang'
  inputs:
    solution: 'PrivacyAmplification/glslang-master/build/glslang.sln'
    platform: 'x64'
    configuration: 'Release'
  
  - task: VSBuild@1
    displayName: 'Build PrivacyAmplification'
    inputs:
      solution: 'PrivacyAmplification/PrivacyAmplification.sln'
      platform: 'x64'
      configuration: 'Release'
      
  - task: CmdLine@2
    displayName: 'CalculateCorrectionFloat Unit Test'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       PrivacyAmplification.exe unitTestCalculateCorrectionFloat
      failOnStderr: true
    
  - task: CmdLine@2
    displayName: 'SetFirstElementToZero Unit Test'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       PrivacyAmplification.exe unitTestSetFirstElementToZero
      failOnStderr: true
    
  - task: CmdLine@2
    displayName: 'ElementWiseProduct Unit Test'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       PrivacyAmplification.exe unitTestElementWiseProduct
      failOnStderr: true
    
  - task: CmdLine@2
    displayName: 'BinInt2float Unit Test'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       PrivacyAmplification.exe unitTestBinInt2float
      failOnStderr: true
    
  - task: CmdLine@2
    displayName: 'ToBinaryArray Unit Test'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       PrivacyAmplification.exe unitTestToBinaryArray
      failOnStderr: true
    
  - task: PythonScript@0
    displayName: 'Generate Stats'
    inputs:
      scriptSource: 'speedtest.py'
    
    #Requires gists.cli.py3 configured with GitHub Token
  - task: CmdLine@2
    displayName: 'Upload Stats'
    inputs:
      script: |
       cd "PrivacyAmplification/bin/Release/"
       gists update dfae7685e20cf3f418559f7960e33cfe ? PrivacyAmpification_RTX_3080_dynamic_seed.svg
       gists update dfae7685e20cf3f418559f7960e33cfe ? PrivacyAmpification_RTX_3080_static_seed.svg
      failOnStderr: true
    
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: 'PrivacyAmplification/bin/Release'
      artifact: 'PrivacyAmplification_$(ShortGitHash)'
      publishLocation: 'pipeline'  
