variables:
  ShortGitHash: ''

jobs:

- job: Build_PrivacyAmplification_On_Self_Hosted_Agent
  timeoutInMinutes: 30
  pool:
    name: PrivacyAmplificationPool

  steps:
  
  - script: |
   set gitHash = $(Build.SourceVersion)
   set shortHash = %gitHash:~0,7%
   echo ##vso[task.setvariable variable=ShortGitHash;]%shortHash%
  
  - task: VSBuild@1
    displayName: 'Build PrivacyAmplification'
    inputs:
      solution: 'PrivacyAmplification/PrivacyAmplification.sln'
      platform: 'x64'
      configuration: 'Release'
      
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'PrivacyAmplification/bin/Release'
      artifact: 'PrivacyAmplification_$(ShortGitHash)'
      publishLocation: 'pipeline'
