address_seed_in: 'tcp://127.0.0.1:45555'
address_key_in: 'tcp://127.0.0.1:47777'
address_amp_out: 'tcp://127.0.0.1:48888'
factor: 27
reduction: 11
pre_mul_reduction: 5
cuda_device_id_to_use: 1
input_blocks_to_cache: 16
output_blocks_to_cache: 16
dynamic_toeplitz_matrix_seed: true
show_ampout: true
use_matrix_seed_server: true
use_key_server: true
host_ampout_server: true
store_first_ampout_in_file: true
toeplitz_seed_path: 'toeplitz_seed.bin'
keyfile_path: 'keyfile.bin'
verify_ampout: true
verify_ampout_threads: 8
