all:
	${MAKE} -f MakefileVulkan.mk
	${MAKE} -f MakefileCuda.mk

vulkan:
	${MAKE} -f MakefileVulkan.mk

cuda:
	${MAKE} -f MakefileCuda.mk

clean:
	${MAKE} -f MakefileVulkan.mk clean
	${MAKE} -f MakefileCuda.mk clean
